@Library('pipeline-shared-libraries')_

pipeline {
    agent any
    stages {
        
        stage('User ID') {
            steps {
		    	echo "Userid : ${utility.getBuildUser()}"
			}
		}
        
        stage('Date') {
            steps {
                script{
    		    	echo "Date : ${utility.getStringDate()}"
    		    	DATE = "${utility.getStringDate()}"
    		    	echo "Is Date a date :  ${utility.isValidStringDate(DATE)}"
                }
			}
		}
    }
}
