pipeline {
    agent any
    tools { 
        maven 'MAVEN3' 
        jdk 'JDK8' 
    }
    stages {
        
        stage('Preparation') {
            steps { 
				script {
                  sh "rm -rf myproject " 
                  
                  sh "'${mavenHome}/bin/mvn' archetype:generate -B " +
                  "-DarchetypeGroupId=org.apache.maven.archetypes " +
                  "-DarchetypeArtifactId=maven-archetype-quickstart " +
                  "-DgroupId=com.company -DartifactId=myproject"
              
                }
			}
		}
		stage('Build') {
			steps {
				script {
                  dir ('myproject') {
                        sh "'${mavenHome}/bin/mvn' clean install test"
                  } 
				}
			}
		}
		stage('Archive') {
			steps {
				script {
                   dir ('myproject/target') {
                       archive '*.jar'
                  } 
				}
			}
		}
    }
}
