node {
      def mavenHome = tool 'MAVEN3'
      def jdkHome = tool 'JDK8'
 
   stage('Preparation') {  
      sh "rm -rf myproject " 
      
      sh "'${mavenHome}/bin/mvn' archetype:generate -B " +
      "-DarchetypeGroupId=org.apache.maven.archetypes " +
      "-DarchetypeArtifactId=maven-archetype-quickstart " +
      "-DgroupId=com.company -DartifactId=myproject"
      
 
   }
   stage('Build') {
        
      dir ('myproject') {
            sh "'${mavenHome}/bin/mvn' clean install test"
      } 
       
   }
   stage('Archive') {
           dir ('myproject/target') {
           archive '*.jar'
      } 
      
   }   
}